#!/usr/bin/env bash

rm -f ~/.tmux.conf
ln -s $(pwd)/tmux/.tmux.conf ~/.tmux.conf

mkdir -p ~/.local/bin
rm -f ~/.local/bin/tmux-sessionizer
ln -s $(pwd)/scripts/tmux-sessionizer ~/.local/bin/tmux-sessionizer
